# -*- coding: utf-8 -*-
"""shape ai project code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10KCu9aBzLtDHCVaqcMjB2rnsbecKSBaj
"""

import requests
from datetime import datetime

api_key = 'a6b6ceccdac3069a47ffb49525f26d15'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

temp_city =((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

f=open('shapeai_weather.txt','w+') 

f.write("Weather Stats for - {}  || {}".format(location.upper(), date_time)+ '\n')
f.write("Current temperature is: {:.2f} deg C".format(temp_city)+'\n')
f.write("Current weather desc  :"+weather_desc +'\n')
f.write("Current Humidity      :"+ (str(hmdt)+ '%')+ '\n')
f.write("Current wind speed    :"+str(wind_spd) +'kmph')
f.close()